apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bumhd6xfc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bumhd6xfc-go 
  name: bumhd6xfc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bumhd6xfc-go 
